### ISSUE TITLE
Reorganização dos módulos, repositórios, pacotes, bibliotecas e infraestrutura

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#1328]

**Comment by igr-santos** [comment]
### Fluxo: Acessar app.staging.bonde.org (Não Autenticado)

- [X] Redirecionamento para accounts.staging.bonde.org com parametro next.
- [X] Carregar aplicação após redirecionamento da autenticação bem sucedida.

### Fluxo: Acessar admin-canary.staging.bonde.org (Não Autenticado)

- [X] Redirecionamento para accounts.staging.bonde.org com parametro next.
- [X] Carregar aplicação após redirecionamento da autenticação bem sucedida.

### Fluxo: Acessar accounts.staging.bonde.org (Não autenticado)
- [X] Redirecionamento para página de autenticação.
- [X] Carregar página com formulário para autenticação.
- [X] Validação do formulário
- [X] Redirecionamento para admin-canary.staging.bonde.org após autenticação bem sucedida.

### Fluxo: Acessar accounts.staging.bonde.org (Autenticado)
- [X] Redirecionamento para admin-canary.staging.bonde.org/login
- [X] Autenticado com sucesso redireciona usuario para admin-canary.staging.bonde.org

### Fluxo: Acessar accounts.staging.bonde.org/register?code=[codigo do convite]
- [x] 1) Carregar formulário de registro de usuário
- [x] 2) Validação do formulário
- [x] 2.1) Se token invalido, informar usuário
- [x] 2.2) Redirecionamento para admin-canary.staging.bonde.org após registro de usuário bem sucedido.

### Fluxo: Convidar usuário
- [X] 1.1. Verificar usuário
- [X] 2.1. Relacionar a comunidade caso usuário existente
- [X] 2.2. Enviar e-mail para usuário informando o convite para comunidade
- [x] 2.3. Link no e-mail deve enviar para accounts.staging.bonde.org/login

- [x] 3.1. Criar convite "code" para comunidade caso usuário não existente.
- [x] 3.2. Enviar e-mail para usuário com link accounts.staging.bonde.org/register?invite={token}.

**Comment by igr-santos** [comment]
Pull-requests:

- https://github.com/nossas/bonde-components/pull/1
- https://github.com/nossas/bonde-core-tools/pull/2
- https://github.com/nossas/bonde-microservices/pull/182
- https://github.com/nossas/bonde-client/pull/1339
- https://github.com/nossas/bonde-auth/pull/28

**Comment by talitanovacoski** [comment]
### Testes Realizados 

**Fluxo: Acessar app.staging.bonde.org (Não Autenticado)** 
O direcionamento funcionou, porém apareceu uma mensagem fora do padrão dizendo “direcionando para o admin” (print em anexo), depois o loading e então o “admin-canary.staging.bonde.org”.

**Fluxo: Acessar admin-canary.staging.bonde.org (Não Autenticado)** 
OK

**Fluxo: Acessar accounts.staging.bonde.org (Não autenticado)**
O direcionamento funcionou, porém demorou cerca de 4 ou 5s pra carregar a pagina com a msg “carregando tradução”. Conseguimos reduzir isso?

**Fluxo: Acessar accounts.staging.bonde.org (Autenticado)** 
OK

**Fluxo: Acessar accounts.staging.bonde.org/register?code=[codigo do convite]** 
Convite de usuário não funcionou.

**Fluxo: Convidar usuário** 
Convite de usuário não funcionou.

**Outro fluxo: Acessar app.staging.bonde.org/mobilizations (Não Autenticado)** 
Direcionou para o accounts, mas depois também apareceu a mensagem fora do padrão dizendo “direcionando para o admin”, depois o loading e então direcionou para o “admin-canary.staging.bonde.org”.

**Outro fluxo: Acessar app.staging.bonde.org/mobilizations (Autenticado)** 
Também apareceu a mensagem fora do padrão dizendo “direcionando para o admin”, depois o loading e então direcionou para o “admin-canary.staging.bonde.org”. Quando autenticado não deveria ir para o mobilizations?

**Outro fluxo: Resetar senha** 
 Fluxo quebrado, leva pra uma tela branca.

#### Outros ajustes mapeados: 

**https://admin-canary.staging.bonde.org/** 
- **navegação:** o ícone de “configurações” aparece ativado, apesar de o usuário não estar nas configurações da comunidade.
- **dropdown do usuário:** tirar “meu perfil” e a miniatura de foto.
- **dropdown de comunidades:** onhover está em cinza escuro, deixar no cinza claro (mesma cor do fundo da tela) 
- **miniatura de comunidades:** deixar redondo na lista e no dropdown de comunidades;

#### Ponto pra discussão:

- **tradução:** algumas traduções não estão corretas, por ex: no inglês o link para recuperar a senha que deveria ser “reset password” aparece como “forget password”, o que seria “esquecer a senha” (um label confuso).. não fiz uma análise mais aprofundada em outras telas e idiomas, mas fiquei na dúvida: será que essa é a melhor solução mesmo? 

Anexo:
![Captura de Tela 2020-04-07 às 14.07.43.png](https://images.zenhubusercontent.com/5e148a9194d5c7299580d128/455487af-9a33-4ad8-9d94-9cf6ef54b493)

**Comment by lpirola** [comment]
Fluxo: Acessar app.staging.bonde.org (Não Autenticado) - ok

Fluxo: Acessar admin-canary.staging.bonde.org (Não Autenticado) - ok

Fluxo: Acessar accounts.staging.bonde.org (Não autenticado) - ok

Fluxo: Acessar accounts.staging.bonde.org (Autenticado) - ok

Fluxo: Acessar accounts.staging.bonde.org/register?code=[codigo do convite] - ao convidar um usuário inexistente ocorre um erro na query com graphql.

```
fetch("https://api-graphql.staging.bonde.org/v1/graphql", {"credentials":"include","headers":{"accept":"*/*","accept-language":"pt-BR,pt;q=0.9,en-GB;q=0.8,en;q=0.7,es-MX;q=0.6,es;q=0.5,en-US;q=0.4","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwb3N0Z3JhcGhxbCIsInJvbGUiOiJhZG1pbiIsInVzZXJfaWQiOjMxLCJpYXQiOjE1ODYzNjgzMTksImF1ZCI6InBvc3RncmFwaGlsZSJ9.Yovu6o3rxLlqp8mSNOvacN4iSlPIlSr69bcdersEA2g","content-type":"application/json","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-site"},"referrer":"https://admin-canary.staging.bonde.org/community/mobilizers","referrerPolicy":"no-referrer-when-downgrade","body":"{\"operationName\":\"Invite\",\"variables\":{\"input\":{\"user_id\":31,\"community_id\":163,\"email\":\"novoemailnovo@nossas.org\",\"role\":2}},\"query\":\"mutation Invite($input: [invitations_insert_input!]!) {\\n  insert_invitations(objects: $input) {\\n    returning {\\n      id\\n      community {\\n        id\\n        name\\n        __typename\\n      }\\n      user_id\\n      created_at\\n      updated_at\\n      expired\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\"}","method":"POST","mode":"cors"});
```

Fluxo: Convidar usuário - ao convidar um usuário já existente um erro na query com graphql acontece.

```
fetch("https://api-graphql.staging.bonde.org/v1/graphql", {"credentials":"include","headers":{"accept":"*/*","accept-language":"pt-BR,pt;q=0.9,en-GB;q=0.8,en;q=0.7,es-MX;q=0.6,es;q=0.5,en-US;q=0.4","authorization":"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJwb3N0Z3JhcGhxbCIsInJvbGUiOiJhZG1pbiIsInVzZXJfaWQiOjMxLCJpYXQiOjE1ODYzNjgzMTksImF1ZCI6InBvc3RncmFwaGlsZSJ9.Yovu6o3rxLlqp8mSNOvacN4iSlPIlSr69bcdersEA2g","content-type":"application/json","sec-fetch-dest":"empty","sec-fetch-mode":"cors","sec-fetch-site":"same-site"},"referrer":"https://admin-canary.staging.bonde.org/community/mobilizers","referrerPolicy":"no-referrer-when-downgrade","body":"{\"operationName\":\"Invite\",\"variables\":{\"input\":{\"user_id\":31,\"community_id\":163,\"email\":\"viviane@nossas.org\",\"role\":2}},\"query\":\"mutation Invite($input: [invitations_insert_input!]!) {\\n  insert_invitations(objects: $input) {\\n    returning {\\n      id\\n      community {\\n        id\\n        name\\n        __typename\\n      }\\n      user_id\\n      created_at\\n      updated_at\\n      expired\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\"}","method":"POST","mode":"cors"});```

**Comment by igr-santos** [comment]
@talitanovacoski sobre **Outro fluxo: Acessar app.staging.bonde.org/mobilizations (Autenticado)**, a regra é a seguinte, se existe comunidade selecionada carrega as mobilizações se não existe redireciona para o admin-canary onde o usuário por escolher uma comunidade, isso é uma particularidade do bonde-admin especificamente por causa do fluxo que ele implementava antigamente para carregar comunidade.

**Comment by talitanovacoski** [comment]
### Terceira rodada de testes

### Ajustes de fluxo

**Acessar o accounts.staging.bonde.org (autenticado)** está pedindo para fazer o login de novo ao invés de direcionar para o admin-canary.staging.bonde.org.

**Acessar o admin-canary.staging.bonde.org e ir para o módulo de redes** - carrega o próprio admin-canary[..] novamente, segundos depois exibe uma tela branca. 

**Acessar o admin-canary.staging.bonde.org e selecionar um módulo de outra comunidade** - sempre que tento acessar outra comunidade, ele carrega o admin-canary.staging.org novamente ao invés de direcionar para o módulo. (enviei um video no slack)

**Chatbot:** ícone do chatbot continua ativo na lista de comunidades mas não direciona a lugar nenhum, carrega o admin-canary.staging.bonde.org e segundos depois exibe a msg em anexo*;

### Ajustes de layout (não impeditivos, mas devem ser endereçados em seguida)

Em **admin-canary.staging.bonde.org**
- corrigir a altura da lista de comunidades para ficar alinhada ao item à direita;
- navegação: o ícone de “configurações” aparece ativado, dando a entender que o usuário está nas configurações da comunidade; **
- dropdown do usuário: tirar o item “meu perfil” e a miniatura de foto.
- dropdown de comunidades: onhover está em cinza escuro, deixar no cinza claro (mesma cor do fundo da tela) 
- miniatura de comunidades: deixar redondo na lista e no dropdown de comunidades, ajustar imagens default (vou enviar na próxima semana);

*
![Captura de Tela 2020-04-09 às 13 38 54](https://user-images.githubusercontent.com/17771695/78918916-83d1b400-7a67-11ea-9406-cbb03c460dbd.png)

**
![image](https://user-images.githubusercontent.com/17771695/78918314-9bf50380-7a66-11ea-9630-f4e3cebdead9.png)

**Comment by vivianedias** [comment]
### Fluxo: Acessar app.staging.bonde.org (Não Autenticado)

- [X] ok
- [X] ok

### Fluxo: Acessar admin-canary.staging.bonde.org (Não Autenticado)

- [X] ok
- [X] ok

### Fluxo: Acessar accounts.staging.bonde.org (Não autenticado)
- [X] ok
- [X] ok
- [X] ok
- [X] ok

### Fluxo: Acessar accounts.staging.bonde.org (Autenticado)
- [ ] Ao entrar pelo accounts.staging.bonde.org (sem autenticar), autenticar, sou redirecionada para o admin-canary.staging.bonde.org. Quando entro de novo no accounts.staging.bonde.org (estando autenticada), eu nao sou redirecionada para o admin-canary. Quando acesso o admin-canary (autenticada), continuo nele, ou seja, ele consegue buscar o token e entender que estou logada, mas no accounts, não.

### Fluxo: Acessar accounts.staging.bonde.org/register?code=[codigo do convite]
- [x] ok
- [ ] nao valida sobrenome, e caso eu nao insira, na tela inicial (admin-canary) o sobrenome fica como "null" inves de nao aparecer nd
- [x] ok
- [x] ok

### Fluxo: Convidar usuário
- [ ] consigo me auto convidar e convidar usuários já participantes da comunidade
- [X] ok
- [X] ok
- [x] ok
- [x] ok
- [x] ok

- [ ] detalhe da tela '/' do admin-canary: quando estou no modo responsivo os ícones somem e quando clico em cima do container da comunidade ela não me leva pra lugar nenhum. Talvez faça sentido adicionar um link nesse container a partir de certo tamanho que redireciona

**Comment by vivianedias** [comment]
@igr-santos o "problema" com o login no accounts que eu e a talita mencionamos acima ainda está acontecendo. acho que não é impeditivo pro release, mas acho q vale pro prox.
