### ISSUE TITLE
[ bonde-webpage ] Migrar para padrão tsdx

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#1355]
- [x] Content
- [ ] Form
- [ ] Donation
- [ ] Pressure

**Comment by vivianedias** [comment]
**UPDATES** 

_24/04_
- Componente de pressão foi finalizado, com renderizações exemplo dos componentes filho no Storybook
- Plugins já migrados (ainda em testes): Content, Form, Draft, Pressure

**To do**
- [ ] Migrar componente de doação
- [ ] Testes passando
- [ ] Continuar enviando analytics para o Google

**Objetivos**
- Manter assinatura dos componentes principais exportados e utilizados em outras bibliotecas p/ minimizar o trabalho de migração da biblioteca
- Todos os testes antigos devem passar
- Mesmo layout
- DraftJS apenas renderiza os conteúdos, não é possível editá-los

**Comment by igr-santos** [comment]
**UPDATES**

- Componente de pressão por e-mail, formulário e conteúdo renderizando no exemplo SSR
- Ambiente de desenvolvimento funcionando com `yarn link`, mais sobre no README do https://github.com/nossas/bonde-webpage
- Adicionado testes para renderização do formulário e pressão por e-mail

**TO DO**

- [ ] Componente pressão por telefone renderizando no exemplo SSR sem apollo-client
- [ ] Componente doação renderizando no exemplo SSR
- [ ] Adicionar testes para componente de pressão por telefone e doação
- [ ] Ambiente de staging rodando com imagem gerada do `bonde-public-ts'

**Comment by vivianedias** [comment]
**UPDATES**

- Adicionamos cobertura de testes de 25%
- Estilização dos plugins Form e Pressure estão 100%
  - O plugin e seus componentes filhos estão no Storybook
- Componente TellAFriend também está renderizado no storybook

**TODO**
- [ ] Terminar o split do plugin de pressão entre telefone/e-mail
- [ ] Testar essa mudança no /example
- [ ] Add mais testes no Pressure
-  Testes que ainda faltam migrar:
  - [ ] Mobilization
  - [ ] Section
  - [ ] Create editor content
- [ ] Verificar se todos os componentes renderizam o font-family com inherit e depois testar
- Pendências:
  - [ ] Novo modo de trackear onBlur no form do pressure p/ analytics por conta do uso do react-final-form

**Comment by igr-santos** [comment]
**UPDATES**

- Chegamos a uma versão em que todos os widgets estão sendo renderizados
- Foi definido o padrão da requisição em APIs GraphQL com o uso do `apollo-fetch`
- Adiciona mais testes no plugin de Pressão

**TODO**
- [ ] É necessario implementar na pressão por telefone as chamadas que são subscriptions
- [ ] Adicionar mais testes unitários
- [ ] Configurar ambiente completo em staging para testes de release

**Comment by vivianedias** [comment]
**Checks para finalização de um plugin:**

- [x] Content

**FinalCustomMessage**
- [ ] Adicionar testes no componente
- [ ] Renderizar um exemplo do componente no storybook

**Form**
- [x] Testes assíncronos para o fluxo de submissão do formulário (erro e sucesso)
- [x] Fazer uso do analytics e garantir que esteja funcionando (testes unitários)

**Pressão por email**
- [x] Testes assíncronos para o fluxo de submissão do formulário (erro e sucesso)
- [x] Fazer uso do analytics e garantir que esteja funcionando (testes unitários)
- [x] Verificar o uso do analytics nos formulários que usam o react-final-form
- [x] Deixar plugin de pressão por e-mail separado do de telefone

**Pressão por telefone** 
- Testes assíncronos para o fluxo de submissão do formulário (erro e sucesso)
- Fazer uso do analytics e garantir que esteja funcionando (testes unitários)
- [x] Verificar o uso do analytics nos formulários que usam o react-final-form
- Acompanhamento assíncrono da chamada com o Twilio
- [x] Deixar plugin de pressão por telefone separado do de email

 **Donation** 
- [ ] Testes assíncronos para o fluxo de submissão do formulário (erro e sucesso)
- [ ] Fazer uso do analytics e garantir que esteja funcionando (testes unitários)
- [x] Integrar o uso do PagarmeJS
- [ ] Fazer o recall para doação recorrente

- [x] Configurar ambiente completo em staging para testes de release

**Comment by igr-santos** [comment]
### Fluxos de funcionamento para uma Doação

**Doação única bem sucedida cartão de crédito**

- Opções de mensagem final: *"Customizada"*, *"Doação Recorrente"* e *"Mensagem Padrão"*.
- Quando *"Doação Recorrente"* deve possibilitar transformar a Doação Única do doador em Recorrente.
- Quando *"Customizada"* ou *"Mensagem Padrão"* deve renderizar seus respectivos componentes.

**Doação única bem sucedida boleto**

- Opções de mensagem final: *"Customizada"*, *"Doação Recorrente"* e *"Mensagem Padrão"*.
- Quando *"Doação Recorrente"* deve renderizar a *"Mensagem Padrão"*.
- Quando *"Customizada"* ou *"Mensagem Padrão"* deve renderizar seus respectivos componentes.

**Doação recorrente bem sucedida cartão de crédito**

- Opções de mensagem final: *"Customizada"*, *"Doação Recorrente"* e *"Mensagem Padrão"*.
- Quando *"Doação Recorrente"* deve renderizar a *"Mensagem Padrão"*.
- Quando *"Customizada"* ou *"Mensagem Padrão"* deve renderizar seus respectivos componentes.

**Doação única / recorrente mal sucedida cartão de crédito / boleto**

- Renderizar o "re-call" para nova tentativa de doação

**Comment by igr-santos** [comment]
@vivianedias vamos atualizar aqui cada problema em um comentário, dessa maneira a gente acompanha o problema e quem está resolvendo ele.

- Agora estou olhando pra pós-ação do Widget de Formulário, vou checar todos os possíveis fluxos e já aplicar as correções necessarias

**Comment by igr-santos** [comment]
- Estou refatorando um código que adiciona um atributo ao bloco usado para iniciar o contador de ações.

**Comment by igr-santos** [comment]
- Problema com o contato de ações foi resolvido, agora estou verificando o motivo serviço em staging não está funcionando corretamente

**Comment by igr-santos** [comment]
Buscando o problema em staging, me deparei com um problema na solução que resolvia o contador de ações, hoje a gente adiciona um evento ao scroll para verificar o momento exato em que o contador precisa iniciar a contagem, esse código era feito com classe e usava o `componentDidMount` ao migrar para função, passando a usar `useEffect` e `useState` esse código me pareceu muito complexo principalmente pelo fato de fazer update no estado do componente causando uma serie de re-renderizações desnecessarias.
