### ISSUE TITLE
Criar API de Notificações para uso amplo na plataforma BONDE

### ISSUE THREAD

**Issue by igr-santos** [nossas/bonde#1395]
O objetivo desse trabalho é:

- Remover a integração email / notificação que hoje está atrelado a base de dados / eventos hasura.
- Criar uma API de Notificação com terminologia genérica que será usada para diversas areas da plataforma BONDE.
```
- Envio em nome do ativista (emaildoativista@provedor.org) (pressão)
- Envio em nome da comunidade (emaildacomunidade@provedor.org) (autofire, mensagens de doação)
- Envio em nome da plataforma (suporte@bonde.org) (reset de senha, cadastro de usuário, convite)
```
- Integrar primeira versão da API com plataforma Sendgrid

**Comment by igr-santos** [comment]
Implementado comunicação com Sendgrid e SMTP:
```
# SENDGRID MODE
# Caso variável não configurada utiliza versão SMTP para envio de e-mail
SENDGRID_API_KEY=
# SMTP MODE
SMTP_HOST=smtp.staging.bonde.org
SMTP_PASS=xxxxxxxx
SMTP_PORT=1025
SMTP_USER=xxxxxxxx
```

**TODO:**

- [x] Padronizar logs
- [ ] Criar testes unitários
- [ ] Criar documentação
- [ ] Alterar inserções na tabela notify_mail para chamadas no método notify
- [ ] Implementar busca por template
- [ ] Donation Boleto Notifications
