### ISSUE TITLE
⚙ Patternize Block module actions as a promise, state components with redux and folder structure

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#275]
# Introduction
As a developer, I want to patternize actions to use it as a promises, refact state components to use redux and restructure directories to follow a pattern.

# Tasks
* [x] Refact actions to use promises (axios) received via thunk
  * [x] fetchBlocks -> async-block-fetch
  * [x] addBlock -> async-block-create
  * [x] editBlock -> async-block-update
  * [x] findBlock -> async-block-select
  * [x] removeBlock -> async-block-destroy
  * [x] moveBlockUp -> async-block-move-up
  * [x] moveBlockDown -> async-block-move-down
* [x] Restructure Block module directories
* [x] ~Refact state components to use redux~

# References
* Pivotal Tracker story: [136226455](https://www.pivotaltracker.com/story/show/136226455)
* Folder structure brief documentation to follow: [ourcities/rebu-client.wiki](https://github.com/ourcities/rebu-client/wiki/Modules-Folder-Structure)

# Branches:
* Migration ancestor branch (base develop): [add/refact-modules](https://github.com/ourcities/rebu-client/tree/add/refactor-modules)
* Working branch (base add/refactor-modules): [add/refactor-block-module](https://github.com/ourcities/rebu-client/tree/add/refactor-block-module)

**Comment by gabrielrtakeda** [comment]
PR https://github.com/ourcities/rebu-client/pull/279
