### ISSUE TITLE
⚙ Patternize Widgets module actions as a promise, state components with redux and folder structure

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#280]
# Introduction
As a developer, I want to patternize actions to use it as a promises, refact state components to use redux and restructure directories to follow a pattern.

# Tasks
* [x] Refact actions to use promises (axios) received via thunk
  * [x] Ancestor widget
    * [x] editWidgetAsync -> async-widget-update
    * [x] fetchWidgets -> async-widget-fetch
    * [x] findWidget -> async-widget-select
  * [x] Content widget
  * [x] Donation widget
  * [x] Draft widget
  * [x] Form widget
  * [x] Match widget
  * [x] Pressure widget
* [x] Restructure Widget module directories
  * [x] Migrate ancestor widget module
  * [x] Migrate **Content** widget plugin
  * [x] Migrate **Donation** widget plugin
  * [x] Migrate **Draft** widget plugin
  * [x] Migrate **Form** widget plugin
  * [x] Migrate **Match** widget plugin
  * [x] Migrate **Pressure** widget plugin
* [x] Refact state components to use redux

Trello board: [refactoring-widgets](https://trello.com/b/aBRe5vep/refactoring-widgets)

# References
* Pivotal Tracker story: [136226481](https://www.pivotaltracker.com/story/show/136226481)
* Folder structure brief documentation to follow: [ourcities/rebu-client.wiki](https://github.com/ourcities/rebu-client/wiki/Modules-Folder-Structure)

# Branches:
* Migration ancestor branch (base develop): [add/refact-modules](https://github.com/ourcities/rebu-client/tree/add/refactor-modules)
* Working branch (base add/refactor-block-module): add/refactor-widgets-module
