### ISSUE TITLE
New public endpoint to edit subscription

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#520]
# Tasks
- [x] `/subscriptions/:id/edit` public route that accepts **token** query string parameter
- [x] Credit card data edit form
e.g. http://app.staging.bonde.org/subscriptions/1/edit?token=d41d8cd98f00b204e9800998ecf8427e
- [x] Recurring data edit form
- [x] Generate **Pagarme** card hash
- [x] Pass the action required fields e.g. (id, token, card_hash and process_at)
- [x] API integration

**Comment by gabrielrtakeda** [comment]
@lpirola What is this about?

**Comment by gabrielrtakeda** [comment]
Add the last used credit card data as reference to the subscriber.
Suggested by @devton

**Comment by gabrielrtakeda** [comment]
Rebase 👇
