### ISSUE TITLE
Translate Community Pages

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#598]
# Tasks

- [x] (admin) /community
- [x] (admin) /community/domain
- [x] (admin) /community/domain/add
- [x] (admin) /community/info
- [x] (admin) /community/mailchimp
- [x] (admin) /community/new
- [x] (admin) /community/recipient
- [x] (admin) /community/report

**Comment by manuellaos** [comment]
@gabrielrtakeda Já se tem uma previsão da atualização da página de  `/community/report` ?

**Comment by manuellaos** [comment]
Rebase 👇

**Comment by gabrielrtakeda** [comment]
Rebase 👇
