### ISSUE TITLE
Translate Mobilizations Pages

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#599]
# Tasks

- [x] (admin) /mobilizations
- [x] (admin) /mobilizations/new
- [x] (admin) /mobilizations/:mobilization_id/analytics
- [x] (admin) /mobilizations/:mobilization_id/basics
- [x] (admin) /mobilizations/:mobilization_id/blocks/create
- [x] (admin) /mobilizations/:mobilization_id/customDomain
- [x] (admin) /mobilizations/:mobilization_id/edit
- [x] (admin) /mobilizations/:mobilization_id/launch
- [x] (admin) /mobilizations/:mobilization_id/launch/end
- [x] (admin) /mobilizations/:mobilization_id/sharing

**Comment by gabrielrtakeda** [comment]
Rebase 👇
