### ISSUE TITLE
Translate Mobilization Templates Pages

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#600]
# Tasks

- [x] (admin) /mobilizations/templates/list
- [x] (admin) /mobilizations/:mobilization_id/templates/choose
- [x] (admin) /mobilizations/:mobilization_id/templates/choose/custom
- [x] (admin) /mobilizations/:mobilization_id/templates/choose/global
- [x] (admin) /mobilizations/:mobilization_id/templates/create

**Comment by gabrielrtakeda** [comment]
Rebase 👇
