### ISSUE TITLE
Translate Donation Widget Pages

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#601]
# Tasks

- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation/autofire
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation/export
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/donation/finish

**Comment by gabrielrtakeda** [comment]
Rebase 👇
