### ISSUE TITLE
Translate Form Widget Pages

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#602]
# Tasks

- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/autofire
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/export
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/fields
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/form/finish

**Comment by gabrielrtakeda** [comment]
Rebase 👇
