### ISSUE TITLE
Translate Pressure Widget Pages

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#603]
# Tasks

- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure/autofire
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure/email
- [x] (admin) /mobilizations/:mobilization_id/widgets/:widget_id/pressure/finish

**Comment by gabrielrtakeda** [comment]
Rebase 👇

**Comment by gabrielrtakeda** [comment]
Rebase 👇
