### ISSUE TITLE
Create a default pt-BR file with all keys

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#614]
# Description
It needs to map the whole system translation entry points and, create a file that contains all the keys.

# Branches
- Working branch (based on: [develop](https://github.com/nossas/bonde-client/tree/develop)): [feature-create-intl-entry-points-with-pt-br](https://github.com/nossas/bonde-client/tree/feature-create-intl-entry-points-with-pt-br)

# Tasks
List of tasks segmented by module (or something that group 'em)

## Other
- [x] /login
- [x] /register
- [x] /account/edit
- [x] /subscriptions/:id/edit

## Community
- [x] /community
- [x] /community/domain
- [x] /community/domain/add
- [x] /community/info
- [x] /community/mailchimp
- [x] /community/new
- [x] /community/recipient
- [x] /community/report

## Mobilization
- [x] /mobilizations
- [x] /mobilizations/new
- [x] /mobilizations/:mobilization_id/analytics
- [x] /mobilizations/:mobilization_id/basics
- [x] /mobilizations/:mobilization_id/blocks/create
- [x] /mobilizations/:mobilization_id/customDomain
- [x] /mobilizations/:mobilization_id/edit
- [x] /mobilizations/:mobilization_id/launch
- [x] /mobilizations/:mobilization_id/launch/end
- [x] /mobilizations/:mobilization_id/sharing

## Mobilization Template
- [x] /mobilizations/templates/list
- [x] /mobilizations/:mobilization_id/templates/choose
- [x] /mobilizations/:mobilization_id/templates/choose/custom
- [x] /mobilizations/:mobilization_id/templates/choose/global
- [x] /mobilizations/:mobilization_id/templates/create

## Donation Widget
- [x] /mobilizations/:mobilization_id/widgets/:widget_id/donation
- [x] /mobilizations/:mobilization_id/widgets/:widget_id/donation/autofire
- [x] ~/mobilizations/:mobilization_id/widgets/:widget_id/donation/export~
- [x] /mobilizations/:mobilization_id/widgets/:widget_id/donation/finish

## Form Widget
- [x] /mobilizations/:mobilization_id/widgets/:widget_id/form
- [x] /mobilizations/:mobilization_id/widgets/:widget_id/form/autofire
- [x] /mobilizations/:mobilization_id/widgets/:widget_id/form/export
- [x] /mobilizations/:mobilization_id/widgets/:widget_id/form/fields
- [x] /mobilizations/:mobilization_id/widgets/:widget_id/form/finish

## Pressure Widget
- [x] /mobilizations/:mobilization_id/widgets/:widget_id/pressure
- [x] /mobilizations/:mobilization_id/widgets/:widget_id/pressure/autofire
- [x] /mobilizations/:mobilization_id/widgets/:widget_id/pressure/email
- [x] /mobilizations/:mobilization_id/widgets/:widget_id/pressure/finish

## Activists Management
- [x] in coming next release based on [Zeplin prototypes](https://zpl.io/1dx3e1)

## Route Paths
- [x] add route path for each translation keys blocks
