### ISSUE TITLE
Script to normalize the slate-editor's nested node

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#641]
# Description
It needs to create a script that normalizes the slate-editor's nested node-image on node-link state object to imageLink node

e.g.
**Current nested nodes object**
```json
{
  "data": {
    "href": "http://www.wishlist.minhasampa.org.br/#block-4572",
    "title": null,
    "target": "_top"
  },
  "kind": "inline",
  "isVoid": false,
  "type": "link",
  "nodes": [
    { "kind": "text", "ranges": [{ "kind": "range", "text": "", "marks": [] }] },
    {
      "data": { "src": "https://s3.amazonaws.com/hub-central/uploads/1492722395_Ativo37.png" },
      "kind": "inline",
      "isVoid": true,
      "type": "image",
      "nodes": [{ "kind": "text", "ranges": [{ "kind": "range", "text": " ", "marks": [] }] }]
    },
    {
      "kind": "text",
      "ranges": [{ "kind": "range", "text": "", "marks": [] }]
    }
  ]
},
```

**Target normalized imageLink object**
```json
{
  "data": {
    "src": "https://s3.amazonaws.com/hub-central/uploads/1492722395_Ativo37.png",
    "title": null,
    "href": "http://www.wishlist.minhasampa.org.br/#block-4572",
    "openExternal": true
  },
  "kind": "inline",
  "isVoid": true,
  "type": "imageLink",
  "nodes": [
    {
      "kind": "text",
      "ranges": [{ "kind": "range", "text": " ", "marks": [] }]
    }
  ]
},
```

# Tasks
- [x] Create a function basing on a simple nested nodes case object and normalize it.
**TIP:** To handle the object and make a deep find, may is a good idea to use libs like [keyfinder](https://www.npmjs.com/package/keyfinder) or [deep-filter-object](https://www.npmjs.com/package/deep-filter-object)
- [x] Get all the content widget objects that uses slate-editor and normalize it with function

**Query to get all content widgets that uses slate-editor**
```sql
SELECT id,
       (settings -> 'content')::json AS content
FROM widgets
WHERE settings -> 'content' ~ '^{"document';
```

- [x] Identify other nested objects cases and cover it

**Comment by gabrielrtakeda** [comment]
# Solution
To solve this, follow the steps described in [Migrate slate object from v2.4 to v2.6](https://github.com/nossas/slate-editor/wiki/Migrate-slate-object-from---v2.4-to-v2.6)
from [nossas/slate-editor](https://github.com/nossas/slate-editor) repository.

**Comment by gabrielrtakeda** [comment]
The migration has already been executed on production database. The affected mobilizations was described in the list below:

**slug**
```
157-mpoa-faca-acontecer
335-minha-casa-sem-policia
342-cpi-da-violencia-contra-a-mulher
344-site-2
353-pela-criacao-da-cpi-das-isencoes-fiscais
358-lista-fechada-nao
359-bike-no-metro
363-participe-do-mandato-marcelo-freixo
364-votacao-do-plano-municipal-de-educacao
365-pela-limpeza-do-canal-do-fragoso
367-instinto-de-vida
368-wishlist
374-culturapresente
376-mapa-moradores-de-rua
377-igualdade-na-escola
382-metas-de-sp-o-que-queremos
385-plano-diretor
387-retira-vinicius
388-merenda-saudavel
389-fora-vidigal
391-cade-o-cache
394-bonde
395-mais-lei-menos-lanche
396-nao-ao-corte-da-gratuidade
397-temer-uniu-o-brasil
399-queremos-conselho-lgbt
400-ruas-abertas
401-pela-aprovacao-da-lei-hip-hop-e-rua
403-so-recebe-quem-vota
412-reducao-de-danos
416-tessssssss
58-institucional-minha-campinas-teste1
85-transporte-publico-campinas
97-meu-recife
99-precisamos-falar-sobre-transporte-publico-em-porto-alegre
```

**Comment by gabrielrtakeda** [comment]
I will check those mobs and, if it is all ok, I will close this issue.
