### ISSUE TITLE
Community members settings changes

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#673]
# Description
It needs to make some changes on the community's members page.

# Tasks
- [x] Add a helper text on top of the page, that give more details about that the form's submit is to invite a person to make them a new mobilizer
- [x] Change the **Membros** tab text to **Mobilizadores**
- [x] Change the **PESSOAS** form label to **EMAIL**

**Comment by gabrielrtakeda** [comment]
Rebase 👇
