### ISSUE TITLE
Community domain settings changes

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#674]
# Description
It needs to make some changes on the community domain settings page.

# Tasks
- On new domain form
  - [x] Step 01: Add a button with **Cancelar**
  - [x] Step 02: Add a button with **Trocar depois**
  - [x] Step 03: Add a button with **Testar depois**
  - [x] Step 02: Change the helper text to:
```
Os Servidores DNS são endereços utilizados pelas organizações de registro de domínios como registro.br ou godaddy.com, para identificarem em qual servidor se encontram as informações sobre o domínio registrado.

Complete a ativação do domínio alterando os servidores DNS, onde o domínio foi registrado, para os endereços abaixo:
```
- [x] Padronizar texto do ícone de sincronizar e o label da etapa 3 do cadastro do domínio
- [x] Remover título da coluna "domínios da comunidade"
- Adicionar ajuda no topo da página de domínios na comunidade
    - [x] Abaixo, encontra-se a lista de domínios já cadastrados. Após alteração e ativação dos servidores DNS, torna-se possível publicar uma mobilização muito mais rápido, além de gerenciar os subdomínios externos cadastrados.
- Adicionar title aos ícones de status do domínio
    - [x] X - Aguardando alteração dos servidores DNS
    - [x] OK - Servidores DNS ativos
- [x] Trocar de "Servidor" para "Servidores" no título
- [x] Alterar mensagem de aviso após testar sincronização para "alteração servidores DNS"
- [x] Remover links de saiba mais nos "Servidores DNS"
- [x] Adicionar parágrafo ao texto de "Servidores DNS"
```
Os Servidores DNS são endereços utilizados pelas organizações de registro de domínios como registro.br ou godaddy.com, para identificarem em qual servidor se encontram as informações sobre o domínio registrado.

Complete a ativação do domínio alterando os servidores DNS, onde o domínio foi registrado, para os endereços abaixo:
```

**Comment by gabrielrtakeda** [comment]
Rebase 👇
