### ISSUE TITLE
Review community config mailchimp and recipients pages

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#675]
# Description

# Tasks

### Community basic info
- [x] Email principal de contato
```patch
- Você deve preencher seguindo o formato padrão: Nome do contato <contato@provedor.com>

+ Esse email é utilizado como remetente padrão das notificações.
```
- [x] Input placeholder:
```
Nome do contato <contato@provedor.com>
```

### Mailchimp page

- [x] Add helper text page

```
A integração com o mailchimp é feita através da criação de segmentos de cada widget criada no BONDE. Adotamos o seguinte padrão no nome dos segmentos: M999P999, M999F999, M999D999
```

- Add helper texts based on [server doc](https://github.com/nossas/bonde-server/blob/master/docs/mailchimp/mailchimp-pt.md)
- [x]  MAILCHIMP API KEY
- [x]  MAILCHIMP ID DA LISTA
- ~MAILCHIMP ID DO GRUPO~

### Recipient page
- [x] Add validation form 
- [x] Improve style form
- [x] Add placeholder to inputs: Digite apenas números / Insira seu nome ou Razão Social
- [x] Add title "Agendamento dos Saques"
- [x] Move warning helper text to subtitle
- [x] Recorrência
- [x] (Semanalmente => Semanal / Mensalmente => Mensal)
- [x] Dia de execução
- [x] Add helper to "Conta bancaria"
```
As doações só serão recebidas após o preenchimento dos dados bancários.

IMPORTANTE: As doações recebidas por uma conta bancária não podem ser transferidas para outra após ela ter sido realizada, ou seja, após serem realizadas as doações o saque sempre será feito para a conta bancária definida no momento da doação.
```

**Comment by gabrielrtakeda** [comment]
@lpirola I do not found the guides to find the **MAILCHIMP ID DO GRUPO** in the [server doc](https://github.com/nossas/bonde-server/blob/master/docs/mailchimp/mailchimp-pt.md)..

**Comment by gabrielrtakeda** [comment]
For now, I'll skip this task

**Comment by gabrielrtakeda** [comment]
@lpirola I just forgot that the task **Add validation form** means heh 😅 
Because the recipient form is already been validated...

**Comment by gabrielrtakeda** [comment]
Follow the screenshot of the recipient page layout:

<img width="1191" alt="screen shot 2017-06-21 at 01 59 16" src="https://user-images.githubusercontent.com/5435389/27367803-473187be-5625-11e7-92d2-bfbf529c78d7.png">

Is there something that I would change?

**Comment by gabrielrtakeda** [comment]
Ooops, I removed the screenshot above, because it contains some personal informations... I'll send it on the slack channel..

**Comment by gabrielrtakeda** [comment]
Rebase 👇
