### ISSUE TITLE
Add Metrics to community page

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#677]
# Tasks
- Create graphql queries
  - [x] Total Ativistas Únicos
  - Total Ativistas Ativos nos últimos 90 dias:
    - ~novos~
    - ~recorrentes~
    - [x] todos
  - Total Ações de pressão nos últimos 90 dias:
    - ~novos~
    - ~recorrentes~
    - [x] todos
  - Total Ações de assinatura nos últimos 90 dias:
    - ~novos~
    - ~recorrentes~
    - [x] todos
  - Valor Total Doações coletadas até agora:
    - [x] chargedback
    - [x] paid
    - [x] refunded
    - [x] refused
    - [x] waiting_payment
  - ~Valor Total Doações disponíveis para saque até agora~
  - [x] Valor Total Doações recorrentes nos últimos 30 dias
  - [x] Valor Total Doações únicas nos últimos 30 dias
  - ~Valor médio de cada doação~
- [x] Add numbers to community
- [x] Add numbers to mobilizations

**Comment by gabrielrtakeda** [comment]
@lpirola for the *Valor Total Doações coletadas até agora* task, the available statuses are:

- chargedback
- paid
- refunded
- refused
- waiting_payment
