### ISSUE TITLE
Remove SSR from admin

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#685]
# Description
It needs to remove the server-side rendering from admin but, keep it on the mobilization's public view.

# Tasks
- [x] Add vhosts to public and admin into express
- [ ] Add html-webpack-plugin to support generate html dist
- [ ] Create [index.html](https://github.com/nossas/vivos-em-nos/blob/master/src/index.html)
- [ ] Remove from development enviroment webpack-express-middleware and hot-reload-express-middleware
- [ ] Add to development enviroment webpack-dev-server to public and admin subdomains
