### ISSUE TITLE
Small UX fixes to community config

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#701]
# Related pull-requests
- Release v0.6.9 #699

# Tasks
- [x]  Página de Informações: Adicionar label para a logo da URL
- [x]  Página de Mobilizadores, trocar o texto: 
```
Ao preencher o campo abaixo, você estará convidando novos mobilizadores para compor sua comunidade.

---------- para

Convide novos usuários para fazerem parte da sua comunidade, eles terão acesso as mesmas informações que o você possui.
Utilizando o formulário abaixo, você envia o convite por e-mail.
```

- Página do Mailchimp: 
- [x]  No primeiro aviso, trocar a cor para amarelo de cuidado!
- [x]  No primeiro aviso, trocar para texto para:

```
A integração com o mailchimp é feita através da criação de segmentos de cada widget criada no BONDE. Adotamos o seguinte padrão no nome dos segmentos: M999P999, M999F999, M999D999

---------- para

Configure a integração com o mailchimp para que seja possível a criação de segmentos dos usuários que interagiram com o sua mobilização nele.
Adotamos o seguinte padrão no nome dos segmentos: M999P000, M999F000, M999D000 (M=MOBILIZAÇÃO, P=PRESSÃO, F=FORMULÁRIO, D=DOAÇÃO)
```

- [x]  Remover o estilo de box de ajuda dos campos api_key e list_id, pois como tudo tem atenção, nada recebe a atenção devida
- [x] Trocar o título dos textos de ajuda "Onde acho essa informação?" dos campos api_key e list_id para "Onde buscar essa informação?"
- [x]  Nos campos api_key e list_id, atualizar os textos de cada ajuda:

```
api_key

No canto superior esquerdo, clique no seu nome de usuário. Em seguida um menu surgirá. Clique na opção account.
---------- para
"Após fazer o login como administrador no mailchimp, clique no seu nome de usuário. Surgirá um menu, clique na opção account."

list_id

Siga os passos: List (no menu) > (Selecione a lista de sua escolha) > Settings > Lists and Defaults
---------- para
1."Após fazer o login como administrador no mailchimp, clique no seu nome de usuário. Surgirá um menu, clique na opção list."
2."Selecione a lista correspondente e siga os passos: Settings > Lists and Defaults"
```
- [x]  Esconder id do grupo na tela do mailchimp, vamos parar de usar essa configuração

- [x]  Página do Recebedor: Mover o aviso de importante para o topo para padronização
- [x]  Página do Recebedor: Atualizar o aviso de importante para:

```
* Informe: Preencha sua conta bancária abaixo para trasferirmos automaticamente as doações recebidas por sua comunidade.

* Atenção 1: Não é possível fazer a transferência de uma doação já recebida para uma nova conta bancária, sempre será utilizada a conta bancária ativa no momento da doação.

* Atenção 2: As doações só ficam disponíveis 31 dias após a transação de cartão de crédito ter sido criada (29 dias corridos + 2 dias úteis) no caso de transações com uma parcela e 2 dias úteis após o pagamento do boleto bancário. Caso a transação tenha de 2 a 12 parcelas, o recebimento normal será da seguinte forma: primeira parcela em 31 dias, segunda em 61, terceira em 91, e assim por diante.
```

- [x]  Página do Recebedor: remover os textos abaixo de cada título de separação do formulário
- [x]  Página do Recebedor ficou muito boa, conseguimos ver tudo que precisamos sem fazer o scroll
