### ISSUE TITLE
Create behaviour to configure pressure via phone

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#762]
# Description
Possibilitar que seja possível cadastrar alvos a serem pressionados por telefone, usando a widget de pressão.

# Tasks
Lista de tarefas:

- [x] Alterar a validação do campo de cadastro de alvos para aceitar email ou telefone
- [x] Detectar automaticamente através do valor entre `<...>` qual tipo de pressão será feita (email ou telefone)
- [x] Adicionar o campo telefone na pressão
- [x] Alterar campo obrigatório para telefone ao invés de email
- [x] Na versão pública, alterar o destinatário para conter telefone e nome
- [x] Tornar possível selecionar um destinatário ou vários que deverão ser pressionados.

**Comment by gabrielrtakeda** [comment]
Rebase 👇

**Comment by gabrielrtakeda** [comment]
Rebase 👇

**Comment by gabrielrtakeda** [comment]
Rebase 👇

**Comment by gabrielrtakeda** [comment]
Rebase 👇

**Comment by gabrielrtakeda** [comment]
Rebase 👇
