### ISSUE TITLE
Create integration with Twilio micro-service

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#763]
# Description
É necessário que seja feita a integração com o [micro-serviço do Twilio](http://github.com/nossas/bonde-phone) para efetuar chamadas de voz com os dados que o usuário inseriu.

# Tasks
Lista de tarefas:

- [x] Criar mutation do GraphQL para criar um novo registro na fila de chamadas
- [x] Criar subscription do GraphQL para observar alterações da máquina de estado das chamadas
- [x] Forçar validação do formato de telefone em `+5511999999999`
- [x] Habilitar funcionalidade de seleção de alvo via propriedade
- [x] Criar interface para controle e manipulação de chamadas
- ~Exibir mensagem de compartilhamento após sucesso da chamada~
- [x] Atualizar contador da widget de pressão
- [x] Remover exibição do número de telefone dos alvos

**Comment by gabrielrtakeda** [comment]
Rebase 👇

**Comment by gabrielrtakeda** [comment]
Rebase 👇

**Comment by gabrielrtakeda** [comment]
Rebase 👇

**Comment by gabrielrtakeda** [comment]
Rebase 👇
