### ISSUE TITLE
Phone pressure v2.1

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#784]
# Related issues
- Phone pressure v2 #779 
- Set the Twilio configurations to community #768

# Description
É necessário que sejam feitas algumas melhorias na funcionalidade de pressão por telefone.

# Tasks
- [x] Add AI to cancel call to bonde-phone
- [x] Add to config API Twillo tokens
- [x] Alterar tabela de solicitação de chamada para conter o id da comunidade
- [x] Efetuar as chamadas usando as configurações de cada comunidade em específico

**Comment by igr-santos** [comment]
PRs related this:

- https://github.com/nossas/bonde-clients/pull/764
- https://github.com/nossas/bonde-clients/pull/818
