### ISSUE TITLE
Phone pressure v3

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#785]
# Description
É necessário que sejam feitas algumas melhorias na funcionalidade de pressão por telefone.

# Tasks
- [ ] Ao clicar nos botões **Ligar** ou **Religar**, mostrar loading como feedback de ação
- [ ] Refatoração da widget de pressão (tentar usar estratégia de plugin: email, phone)
- [ ] Integrar WebSocket no BONDE
- [ ] Trocar watch query de `pollInterval` para `subscription` do GraphQL

**Comment by igr-santos** [comment]
PRs related this:

- Feature phone pressure #764
- Add support to pressure by phone #818
