### ISSUE TITLE
Add goal progress bar to donation widget

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#814]
# Tasks
- [x] Implementar barra de progresso no estilo bulma (sem a dependência do pacote bulma completo)
- [x] Adicionar opção de configurar meta de doação na página de configuração da widget de doação
- [x] Resgatar informações da meta de doação via GraphQL nossas/bonde-server#368
- [x] Integrar informações resgatadas na widget de doação
- [x] Adicionar data para alcançar a meta

Observação: Exibir barra de progresso da meta de doação apenas se houver meta de doação configurada.
