### ISSUE TITLE
Facebook bot mass message

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#829]
# Description
É necessário que seja feito o envio de mensagem em massa, inicialmente, para os usuários que interagiram com a robô do feminista: [BETA](https://m.me/beta.feminista)

# Tasks
- [x] Criar rota provisória para que, apenas quem possuir o link consiga acessar
- [x] Criar tabela `facebook_bot_activists` para manter os dados de ativistas únicos
- [x] Criar trigger para criar ou atualizar novo registro de ativista em `facebook_bot_activists`
- Implementar feature de filtro na listagem de usuários
  - [x] Filtro por: **quick reply**
  - [x] Filtro por: **mensagem do usuário**
  - [x] Filtro por: **período de data**
  - [x] Filtro por: **período de data** e **quick reply**
  - [x] Filtro por: **período de data** e **mensagem do usuário**
  - [x] Filtro por: **período de data**, **mensagem do usuário** e **quick reply**
  - [x] Filtro por: **mensagem do usuário** e **quick reply**
- [x] Exibir quantidade de ativistas que receberão a mensagem em massa
- [x] Exibir apenas últimos 50 ativistas da segmentação
- [x] Criar formulário de segmentação dos ativistas
- [x] Criar formulário de preenchimento da mensagem que será enviada
- [x] Criar validação para os formulários
- [x] Criar queries graphql para segmentação dos ativistas
- ~Efetuar requisição post com lista de `recipientId` pro micro-serviço [bonde-bot](https://github.com/nossas/bonde-bot)~
~> nossas/bonde-bot#48
- [x] Configurar envio de mensagem com opção de botão quick reply
- [x] Criar step de sucesso

**Comment by lpirola** [comment]
@gabrielrtakeda na requisição POST com a lsita de recipientId, tenho a impressão que podemos esbarrar no limite do tamanho da string que enviaremos no POST. Chegou a pensar sobre isso?

**Comment by gabrielrtakeda** [comment]
@lpirola pode crê mano não tinha pensado nisso mas, tava sentindo que tinha algo de errado... kkk
Cheguei até a pensar em fazer um listen notify lá no banco quando for enviado uma mensagem em massa.. Tipo, criar uma tabela que salva a mensagem que deve ser enviada (o @devton já havia comentado disso comigo), com uma coluna que tem todos os `recipientId` e, quando tiver um `INSERT` nessa tabela, dispara uma notificação que o micro-serviço do **bonde-bot** já vai estar esperando.. O que acha...?

**Comment by lpirola** [comment]
@gabrielrtakeda acho que pode ser mais complicado do que imaginamos incluir esse processo de notify. Já pensou em usar o redis para fazer uma fila e enviar em "batches" os recipientsId?

**Comment by gabrielrtakeda** [comment]
Abri a issue abaixo no bonde-bot:
**Queue to process the mass message sending nossas/bonde-bot#48**

**Comment by gabrielrtakeda** [comment]
Rebase 👇
