### ISSUE TITLE
Improve CRM design

### ISSUE THREAD

**Issue by lpirola** [nossas/bonde#837]
# Description
É necessário melhorar o layout da funcionalidade de CRM

# Tasks
- ~Abrir CRM com lista geral de ativistas~
- [x] Incluir loading local no grid
- [x] Melhor organizar a barra fixa de detalhes do ativista
- [x] Atualizar estilos do filtro por tag e do filtro por data
- [x] Atualizar grid para centralizar

**Comment by lpirola** [comment]
@gabrielrtakeda @ton pelo que o @igr-santos comentou que já estamos fazendo uma busca inicialmente mas o backend retorna vazio, talvez tenha que alterar lá.

**Comment by ton** [comment]
Please don't ping me on this.
