### ISSUE TITLE
Bot mass message campaign

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#885]
# Related external repository issues

- Save bot mass message campaign nossas/bonde-server#381
- Save bot mass message campaign nossas/bonde-bot#69

# Description

É necessário que seja salva a campanha de envio de mensagem em massa para os usuários que interagiram com o bot, como forma de manter o histórico.

# Tasks

**Layout de settings page**
- [ ] Título da página: Campanhas da BETA
- [ ] Adicionar página de bot no layout com sidebar
- [ ] Configurar duas abas: histórico de campanhas / nova campanha

**Etapa de segmentação por campanha**
- [ ] Título "Envio de mensagem em massa" trocar para Segmentação da campanha
- [ ] Título da Etapa 1: Utilizar campanhas anteriores como filtro
- [ ] Combo: "Incluir/Excluir" usuários baseado nas campanhas abaixo:
- [ ] Campo como tags para multi seleção por nome das campanhas existentes 
- [ ] Título da Etapa 2: Filtros básicos

**Filtro de exclusão de usuários por campanha**
- [x] Implementar integração com função do GraphQL para "desselecionar" os ativistas segmentados que pertencem as campanhas escolhidas
