### ISSUE TITLE
code coverage support

### ISSUE THREAD

**Issue by gabrielrtakeda** [nossas/bonde#989]
# pivotal
> [[#159073711]](https://www.pivotaltracker.com/story/show/159073711) Como desenvolvedor gostaria de ter o code coverage do client para saber quais partes estão mais vulneráveis

# objetivo
> cobertura de código em todos os packages.

# tasks
- [x] estudo e laboratório
> **bonde-admin**
- [x] adicionar regra `**/*.spec.js` em **.babelrc** e **.nycrc**
- [x] adicionar script `coverage` e `coverage:report`
- [x] ignorar arquivos e diretórios gerados pelo comando `coverage` em **.gitignore** e **.npmignore**
> **bonde-admin-canary**
- [ ] adicionar regra `**/*.spec.js` em **.babelrc** e **.nycrc**
- [ ] adicionar script `coverage` e `coverage:report`
> **bonde-public**
- [ ] adicionar regra `**/*.spec.js` em **.babelrc** e **.nycrc**
- [ ] adicionar script `coverage` e `coverage:report`
> **bonde-styleguide**
- [ ] adicionar regra `**/*.spec.js` em **.babelrc** e **.nycrc**
- [ ] adicionar script `coverage` e `coverage:report`
> **bonde-webpage**
- [ ] adicionar regra `**/*.spec.js` em **.babelrc** e **.nycrc**
- [ ] adicionar script `coverage` e `coverage:report`
